/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdmissionSubmission = IDL.Record({
  'email' : IDL.Opt(IDL.Text),
  'message' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'childName' : IDL.Text,
  'childClass' : IDL.Text,
  'parentName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSubmission' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listSubmissions' : IDL.Func([], [IDL.Vec(AdmissionSubmission)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdmissionSubmission = IDL.Record({
    'email' : IDL.Opt(IDL.Text),
    'message' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'childName' : IDL.Text,
    'childClass' : IDL.Text,
    'parentName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSubmission' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listSubmissions' : IDL.Func([], [IDL.Vec(AdmissionSubmission)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };